sudo: false
language: java
jdk: oraclejdk11

addons:
  sonarcloud:
    organization: "smabotics-github" # the key of the org you chose at step #3
    branches:
      - master
      - makePull
script:
#   - chmod +x ./gradlew
#   #- ant -f travis.build.xml
  # other script steps might be done before running the actual analysis
  - sonar-scanner 
  